# Generated by Django 3.0.8 on 2020-07-19 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(max_length=100, validators=[django.core.validators.EmailValidator]),
        ),
    ]
